# Generated by Django 2.2.2 on 2019-06-06 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20190529_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='todo.Category'),
        ),
    ]
